{"name": "Verify Calculation", "status": "failed", "statusDetails": {"message": "Failed: An error has occurred...see details:", "trace": "self = <selenium_automation.lesson03.super_calculator_v2.Test_Super_Calculator_V2 object at 0x0000028D146734F0>\n\n    @allure.title(\"Verify Calculation\")\n    @allure.description(\"The function will keep calculating until provided number\")\n    def test_calculate(self):\n        try:\n            self.calculate()\n>           self.print_result()\n\nlesson03\\super_calculator_v2.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\na = (<selenium_automation.lesson03.super_calculator_v2.Test_Super_Calculator_V2 object at 0x0000028D146734F0>,), kw = {}, __tracebackhide__ = True\nparams = OrderedDict(), args = ['<selenium_automation.lesson03.super_calculator_v2.Test_Super_Calculator_V2 object at 0x0000028D146734F0>']\n\n    @wraps(func)\n    def impl(*a, **kw):\n        __tracebackhide__ = True\n        params = func_parameters(func, *a, **kw)\n        args = list(map(lambda x: represent(x), a))\n        with StepContext(self.title.format(*args, **params), params):\n>           return func(*a, **kw)\n\n..\\venv\\lib\\site-packages\\allure_commons\\_allure.py:172: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium_automation.lesson03.super_calculator_v2.Test_Super_Calculator_V2 object at 0x0000028D146734F0>\n\n    @allure.step(\"Print Result of calculation\")\n    def print_result(self):\n        td = driver.find_elements(By.XPATH, \"//td[@class='ng-binding']\")\n        for i in range(1, len(td), 2):\n>           sum += int(td[i].text)\nE           UnboundLocalError: local variable 'sum' referenced before assignment\n\nlesson03\\super_calculator_v2.py:102: UnboundLocalError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <selenium_automation.lesson03.super_calculator_v2.Test_Super_Calculator_V2 object at 0x0000028D146734F0>\n\n    @allure.title(\"Verify Calculation\")\n    @allure.description(\"The function will keep calculating until provided number\")\n    def test_calculate(self):\n        try:\n            self.calculate()\n            self.print_result()\n        except Exception as e:\n            self.attach_file()\n>           pytest.fail(\"An error has occurred...see details:\", e)\nE           Failed: An error has occurred...see details:\n\nlesson03\\super_calculator_v2.py:43: Failed"}, "description": "The function will keep calculating until provided number", "steps": [{"name": "Calculate until provided number", "status": "passed", "steps": [{"name": "Navigate inside the iframe", "status": "passed", "start": 1639486527245, "stop": 1639486527267}, {"name": "Generate Random Number", "status": "passed", "parameters": [{"name": "min_number", "value": "'5'"}, {"name": "max_number", "value": "'3'"}], "start": 1639486527267, "stop": 1639486528458}, {"name": "Store the Random Number", "status": "passed", "start": 1639486528458, "stop": 1639486528472}, {"name": "Navigate to Calculator", "status": "passed", "start": 1639486528472, "stop": 1639486528983}, {"name": "Filling inputs", "status": "passed", "parameters": [{"name": "first_value", "value": "3"}, {"name": "operator", "value": "'*'"}, {"name": "second_value", "value": "2"}], "start": 1639486528983, "stop": 1639486529156}, {"name": "Filling inputs", "status": "passed", "parameters": [{"name": "first_value", "value": "3"}, {"name": "operator", "value": "'*'"}, {"name": "second_value", "value": "1"}], "start": 1639486531157, "stop": 1639486531254}, {"name": "Filling inputs", "status": "passed", "parameters": [{"name": "first_value", "value": "3"}, {"name": "operator", "value": "'*'"}, {"name": "second_value", "value": "0"}], "start": 1639486533254, "stop": 1639486533353}], "start": 1639486527245, "stop": 1639486535353}, {"name": "Print Result of calculation", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'sum' referenced before assignment\n", "trace": "  File \"c:\\automation\\python\\test_automation\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Automation\\Python\\test_automation\\selenium_automation\\lesson03\\super_calculator_v2.py\", line 102, in print_result\n    sum += int(td[i].text)\n"}, "start": 1639486535353, "stop": 1639486535365}, {"name": "Attaching a screenshot to the report", "status": "passed", "attachments": [{"source": "4e3f8a03-cd98-42d1-820b-d089bc86aa63-attachment.png", "type": "image/png"}], "start": 1639486535366, "stop": 1639486535477}], "attachments": [{"name": "log", "source": "75e1544d-5923-4d24-9342-b8eb146f9b1f-attachment.txt", "type": "text/plain"}], "start": 1639486527244, "stop": 1639486535477, "uuid": "bbaf14c9-ff67-413c-bfc7-0fcb319d090c", "historyId": "38d9e6c3d8fee6c5bda1b8656124b340", "testCaseId": "cb0f3a011feb18e5a7d198933ecb5b12", "fullName": "lesson03.super_calculator_v2.Test_Super_Calculator_V2#test_calculate", "labels": [{"name": "parentSuite", "value": "lesson03"}, {"name": "suite", "value": "super_calculator_v2"}, {"name": "subSuite", "value": "Test_Super_Calculator_V2"}, {"name": "host", "value": "DESKTOP-LVSINNE"}, {"name": "thread", "value": "20124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "lesson03.super_calculator_v2"}]}